services:
  postgres:
    image: postgres:16
    container_name: todoapp-db
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: